version: "3"

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    # prettier-ignore
    ports: 
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    # prettier-ignore
    ports: 
      - "8001:8001"

  films:
    container_name: films
    restart: always
    build: ./films
    # prettier-ignore
    ports: 
      - "8002:8002"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    # prettier-ignore
    ports: 
      - "8003:8003"

  database:
    container_name: database
    restart: always
    build: ./database
    # prettier-ignore
    ports: 
      - "8004:8004"
